name: Prevent Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this was a direct push
        run: |
          echo "❌ Direct push to main is not allowed!"
          exit 1